### ISSUE TITLE
Shared external window

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#2]
When multiple instances are used, the external window should (optionally) be reused among instances

**Comment by JaySunSyn** [comment]
It looks like that this is already happening on my machine.
(PR https://github.com/Neovici/cosmoz-image-viewer/pull/5)

Do I get something wrong?

**Comment by nomego** [comment]
Hmm I did test this yesterday and what I mean is that we need a way for one instance to hijack another instance. For example, in data-nav we might have multiple views with image-viewer, if the user detaches to image into an external window and then switches to the next instance, it should detach itself and re-use the window from the previous instance. (This might want to be configurable though.)
So we need a way to say which instance is the active one as well. (Since both will be present in the DOM)
