### ISSUE TITLE
Misc fixes needed

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#32]
- [x] CSS spinner / loading when images are loading (replaced/changing)
- [ ] Transitions when switching images in detached window(?)
- [x] Show current + total page numbers in detached window
- [x] Disable prev/next in detached window when on first/last (or loop)
- [x] Consider putting detached window template into an actual `<template>`
- [ ] Split up JS into behaviors (detached, pan-zoom?)

**Comment by JaySunSyn** [comment]
Re: Consider putting detached window template into an actual

I actually did that in the beginning; Ajax loaded the html file and wrote it into the external window; Works well in the element itself;

When building the app though, I think that we would need to add the dependency in `extraDependencies` to keep the path valid.

Not sure what's better...

**Comment by nomego** [comment]
Actually the description was incomplete because I didn't escape the `<template>` tag.
What I meant was to move it into a template tag and extract the content and import a node into the created window. I think this is a pretty spot-on use case for the template html standard (even if we're used to using it with Polymer). I might have a go at this during the week.

**Comment by JaySunSyn** [comment]
Hmm I see, `preserve-content` did the trick for me now. I think that I tried that before somewhere but always got empty fragments.

Something like this? 

https://github.com/Neovici/cosmoz-image-viewer/compare/master...JaySunSyn:master
