### ISSUE TITLE
skeleton-carousel strategy

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#33]
We currently depend on `JaySunSyn/skeleton-carousel#hybrid`.
Any reason why this can be PR'ed/merged upstream to `FabricElements/skeleton-carousel`?
What do we lack upstream?

If we need custom features that won't be merged upstream, we need to have them in a Neovici repo fork.

**Comment by JaySunSyn** [comment]
Everything is merged on upstream. 
I now asked to release a new "hybrid" version.
I'll change the dependency when done.

**Comment by nomego** [comment]
Done @JaySunSyn ?
