### ISSUE TITLE
External window tests

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#39]
- [x] Test opening/controlling external window
- [x] Popup-blocker tests
- [x] Test "taking" a window with another instance (shared)
- [x] Test opening a window, refreshing the page, and re-attaching to (now unknown) window
- [ ] Make sure test coverage etc is handled for external window template script

**Comment by nomego** [comment]
Are all fixed @JaySunSyn ?

**Comment by JaySunSyn** [comment]
First 4 fixed (where possible). Not 100% sure about coverage. Will look into it. But the issue can be closed. thx
