### ISSUE TITLE
Improve tests, use callbacks/events instead of timeouts

### ISSUE THREAD

**Issue by programmer4web** [Neovici/cosmoz-image-viewer#50]
chrome 67 [1.x]          :heavy_multiplication_x: test/basic.html » cosmoz-image-viewer-loading-error » error is shown with img-pan-zoom active
 expected true to equal false

**Comment by programmer4web** [comment]
[WIP]

**Comment by nomego** [comment]
@cristinecula Still relevant?

**Comment by cristinecula** [comment]
@nomego I can't find the mentioned test in `test/basic.html`. I also searched through the git log and can't find it. The tests do not have async issues at the moment, so I think this is not relevant anymore.
