### ISSUE TITLE
Downloading images yields corrupt .png

### ISSUE THREAD

**Issue by fredrikbernholm** [Neovici/cosmoz-image-viewer#51]
Download images can't be opened correctly. System says file is corrupt.

**Comment by fredrikbernholm** [comment]
Tested in beta 3.3.9.

**Comment by JaySunSyn** [comment]
Thx @fredrikbernholm. It seems like there is an issue with the paths of the images in FE. But would need to check that in beta. (waiting for access)

**Comment by JockeCK** [comment]
Took an look, seems to be an case of double slash in the path. I don't think this can be fixed here in the component. Will make sure then close this issue if true.

**Comment by JockeCK** [comment]
Not that easy, turns out this is a matter of access rights and sessions. getting 401, still not an cosmoz-image-view issue though.

**Comment by JockeCK** [comment]
Created PR(see ref above) since of course actually this did need to be fixed in cosmoz-image-viewer. ( To uphold the tradition of me taking back everything I assume, you would think I would learn. )

**Comment by JockeCK** [comment]
Fix has been merged and an new release released. Closing isssue
