### ISSUE TITLE
Evaluate if we still need to debounce image change for dom-repeat

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#60]
https://github.com/Neovici/cosmoz-image-viewer/blob/12de0bf072a81b92e03ebbf6e9bbcffdcc2a2c07/cosmoz-image-viewer.js#L652

See #21 and #22

**Comment by cristinecula** [comment]
@nomego I have tried to remove the debouncer, but the problem it works around still persists.

**Comment by nomego** [comment]
@cristinecula Ok but we should still drop `Polymer.dom.addDebouncer` ?

**Comment by cristinecula** [comment]
@nomego yes, we should use https://polymer-library.polymer-project.org/2.0/api/classes/Polymer.Debouncer#staticmethod-debounce instead.

**Comment by nomego** [comment]
Would things be different if we moved this component to lit-element?

**Comment by cristinecula** [comment]
Yes. The version I'm working on for https://github.com/Neovici/cosmoz-image-viewer/issues/69 does not suffer from this issue. We could alternatively fix the issue in `img-pan-zoom` and then drop the debouncer.

**Comment by nomego** [comment]
@cristinecula also fixed by #74  ?

**Comment by cristinecula** [comment]
It seems that the bug actually originates in skeleton-carousel, but #74 has a different workaround for the issue, which does not use a debouncer.

**Comment by nomego** [comment]
Ok, closing then.
