### ISSUE TITLE
Scroll to zoom on desktop

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-image-viewer#75]
After switching to haunted-pan-zoom, I'm unable to scroll the images with the scroll wheel, I think the user should be able to. (Even further than 100%)

**Comment by cristinecula** [comment]
We have the opportunity to alter the pan-zoom behavior to better fit our use. 

The current behavior is this:
1. upon load, the image is centered and scaled to fit inside the container
2. when the user taps the zoom icon, the pan-zoom element becomes interactive and zooms in to zoom level 1.5
3. when the user scrolls, the image is scaled, but there are limits to this zoom: the min zoom level is the initial scaled-to-fit zoom level (zoom: 1); the max zoom level is not fixed and is determined by the maxZoomPixelRatio value (currently 1.1), i.e. you can zoom in until the image is 110% it's original (natural) dimensions. If an image is already scaled up more than 110% at zoom level 1, then zooming is effectively disabled by these rules.

I can adjust the max ratio to a higher value, but this will result in blurry images.

**Comment by cristinecula** [comment]
I will change the max zoom algorithm so that you can zoom in until the image is 110% it's original (natural) dimensions or until 25% of the image covers the container, whichever gives the largest zoom level.
